plugins:
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  DisplayCopNames: true

Layout/LineLength:
  Max: 120
  IgnoredPatterns: '\A#'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Max: 30

Style/Documentation:
  Enabled: false